# Generated by Django 5.2.11 on 2026-03-05 17:18

import Connections.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigIntegerField(default=Connections.models.generate_connection_id, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('blocked', 'Blocked'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('unfriend_at', models.DateTimeField(blank=True, null=True)),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FriendShip',
                'verbose_name_plural': 'FriendShips',
                'ordering': ['-created_at'],
                'unique_together': {('user1', 'user2')},
            },
        ),
        migrations.CreateModel(
            name='FriendMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_notification', models.CharField(choices=[('email', 'email'), ('message', 'message')], default='email', max_length=10)),
                ('user2_notification', models.CharField(choices=[('email', 'email'), ('message', 'message')], default='email', max_length=10)),
                ('user1_muted', models.BooleanField(default=False)),
                ('user2_muted', models.BooleanField(default=False)),
                ('theme', models.ImageField(blank=True, null=True, upload_to='text_theme/')),
                ('user1_nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('user2_nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Connections.friend')),
            ],
            options={
                'verbose_name': 'MetaFriendship',
                'verbose_name_plural': 'MetaFriendships',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('unblocked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Blocked_user', to=settings.AUTH_USER_MODEL)),
                ('blocker_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocker_user', to=settings.AUTH_USER_MODEL)),
                ('friend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='Connections.friend')),
            ],
            options={
                'unique_together': {('blocker_user', 'blocked_user')},
            },
        ),
    ]
