# Generated by Django 5.2.11 on 2026-03-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('blocked', 'blocked'), ('rejected', 'rejected')], default='pending', max_length=10),
        ),
    ]
