# Generated by Django 5.2.11 on 2026-02-28 15:40

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContextMessages',
            fields=[
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
            ],
            options={
                'managed': False,
            },
        ),
    ]
