# Generated by Django 6.0.2 on 2026-02-25 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('visibility', models.CharField(choices=[('Private', 'private'), ('Public', 'public')], default='public', max_length=10)),
                ('joining_code', models.CharField(blank=True, max_length=100, null=True)),
                ('activity', models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive')], default='active', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(choices=[('Creator', 'creator'), ('Manager', 'manager'), ('Bot', 'bot'), ('Normal', 'normal'), ('Guest', 'guest')], default='normal', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_members', to='Clans.clan')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_member_of', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('clan', 'member')},
            },
        ),
    ]
