# Generated by Django 5.2.11 on 2026-03-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='member_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
