# Generated by Django 6.0.2 on 2026-02-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
