# Generated by Django 6.0.2 on 2026-02-26 18:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clans', '0002_alter_clan_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='members',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='members',
            constraint=models.UniqueConstraint(fields=('clan', 'member'), name='unique_clan_member'),
        ),
    ]
